### ISSUE TITLE
Issue with new installer?

### ISSUE THREAD

**Issue by Mizpah** [AcroMedia/commerce-demo#65]
Hi folks,

firstly, many thanks for your multiple ressources out in the community!

Running 'inv setup' errors as below (ModuleNotFoundError: No module named 'boto3')
 
Full error:

mizpah@DESKTOP-07BD7MR:~/hipster$ inv setup
Traceback (most recent call last):
  File "/usr/bin/inv", line 11, in <module>
    load_entry_point('invoke==1.3.0', 'console_scripts', 'inv')()
  File "/usr/lib/python3/dist-packages/invoke/program.py", line 373, in run
    self.parse_collection()
  File "/usr/lib/python3/dist-packages/invoke/program.py", line 465, in parse_collection
    self.load_collection()
  File "/usr/lib/python3/dist-packages/invoke/program.py", line 696, in load_collection
    module, parent = loader.load(coll_name)
  File "/usr/lib/python3/dist-packages/invoke/loader.py", line 76, in load
    module = imp.load_module(name, fd, path, desc)
  File "/usr/lib/python3.8/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.8/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mizpah/hipster/tasks/__init__.py", line 2, in <module>
    import boto3
ModuleNotFoundError: No module named 'boto3'

**Comment by Mizpah** [comment]
Managed to answer my own query - from digging around the repo, this is a python script used to install. (have never seen this with lando!)

By updating component's on my wsl ubuntu, this now runs!

sudo apt-get install python3-pip
sudo pip3 install boto3

Note: your environment is probably different, but that's the gist of the isssue!
